name: async_wrapper
description: >
  A generic Flutter widget that simplifies managing loading, success, and error
  states in asynchronous operations with a clean builder pattern.
version: 1.0.0
homepage: https://github.com/FrancescoVenanti/async_wrapper
repository: https://github.com/FrancescoVenanti/async_wrapper

topics:
  - async
  - state
  - widget
  - flutter
  - buttons

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0

flutter:
  uses-material-design: true
