name: async_wrapper
description: A lightweight Flutter package for handling async operations with built-in loading, success, and error states.
version: 1.0.0
homepage: https://github.com/FrancescoVenanti/async_wrapper
repository: https://github.com/FrancescoVenanti/async_wrapper

topics:
  - async
  - state
  - widget
  - flutter
  - buttons

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  lints: ^3.0.0

flutter:
  uses-material-design: true
